version: "3"

services:
  comments-svc:
    image: "comments-svc:test"
    container_name: "comments-svc"
    build:
      context: "./grpc-services/comments"
      dockerfile: "Dockerfile.test"
    networks:
      - "frontend"
      - "backend"
      - "commentsdomain"
    expose:
      - "50051"
    depends_on:
      - "comments-db"
      - "cache"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
      DB_NAME: "postgres"
      DB_HOST: "comments-db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  posts-svc:
    image: "posts-svc:test"
    container_name: "posts-svc"
    build:
      context: "./grpc-services/posts"
      dockerfile: "Dockerfile.test"
    networks:
      - "frontend"
      - "backend"
      - "postsdomain"
    expose:
      - "50051"
    depends_on:
      - "posts-db"
      - "cache"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
      DB_NAME: "postgres"
      DB_HOST: "posts-db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  users-svc:
    image: "users-svc:test"
    container_name: "users-svc"
    build:
      context: "./grpc-services/users"
      dockerfile: "Dockerfile.test"
    networks:
      - "frontend"
      - "backend"
      - "usersdomain"
    expose:
      - "50051"
    depends_on:
      - "users-db"
      - "cache"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
      DB_NAME: "postgres"
      DB_HOST: "users-db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  mailer-svc:
    image: "mailer-svc:test"
    container_name: "mailer-svc"
    build:
      context: "./grpc-services/mailer"
      dockerfile: "Dockerfile.test"
    networks:
      - "frontend"
      - "mailerdomain"
    expose:
      - "50051"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  graphql-gateway:
    image: "graphql-gateway:test"
    container_name: "graphql-gateway"
    build:
      context: "./graphql-gateway"
      dockerfile: "Dockerfile.test"
    networks:
      - "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - "cache"
      - "comments-svc"
      - "posts-svc"
      - "users-svc"
      - "mailer-svc"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "3000"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
      JWT_SECRET: "47YNbpelXTd2gAi+6r1C4bDj4NSlxUDS"
      COMMENTS_SVC_URL: "comments-svc:50051"
      POSTS_SVC_URL: "posts-svc:50051"
      USERS_SVC_URL: "users-svc:50051"
      MAILER_SVC_URL: "mailer-svc:50051"
    healthcheck:
      test: ["CMD", "wget", "localhost:3000/healthz -q -O - > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  comments-db:
    image: "postgres:11.4-alpine"
    container_name: "comments-db"
    networks:
      - "commentsdomain"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "on-failure"

  posts-db:
    image: "postgres:11.4-alpine"
    container_name: "posts-db"
    networks:
      - "postsdomain"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "on-failure"

  users-db:
    image: "postgres:11.4-alpine"
    container_name: "users-db"
    networks:
      - "usersdomain"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "on-failure"

  cache:
    image: "redis:5.0.5-alpine"
    container_name: "redis-cache"
    networks:
      - "frontend"
      - "backend"
    expose:
      - "6379"
    restart: "on-failure"

networks:
  frontend:
  backend:
  commentsdomain:
  postsdomain:
  usersdomain:
  mailerdomain:
