version: "3"

services:

  comments-svc:
    build:
      context: "."
    networks:
      - "comments-svc"
    ports:
      - "50051:50051"
    depends_on:
      - "db"
      - "cache"
    environment:
      NODE_ENV: "test"
      HOST: "0.0.0.0"
      PORT: "50051"
      DB_NAME: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  db:
    image: "postgres:11.4-alpine"
    networks:
      - "comments-svc"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "on-failure"

  cache:
    image: "redis:5.0.5-alpine"
    networks:
      - "comments-svc"
    expose:
      - "6379"
    restart: "on-failure"

networks:
  comments-svc:
